spring:
    datasource:
        url: jdbc:h2:tcp://localhost:1521/test
        driverClassName: org.h2.Driver
        username: sa
        password:
    sql:
      init:
        encoding: UTF-8
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
          ddl-auto: create-drop
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            format-sql: true
            show-sql: true
    h2:
      console:
        enabled: true
        path: /h2-console